<?php

use Illuminate\Database\Seeder;

class PermissionSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items = [
            
            ['id' => 1, 'title' => 'user_management_access',],
            ['id' => 2, 'title' => 'permission_access',],
            ['id' => 3, 'title' => 'permission_create',],
            ['id' => 4, 'title' => 'permission_edit',],
            ['id' => 5, 'title' => 'permission_view',],
            ['id' => 6, 'title' => 'permission_delete',],
            ['id' => 7, 'title' => 'role_access',],
            ['id' => 8, 'title' => 'role_create',],
            ['id' => 9, 'title' => 'role_edit',],
            ['id' => 10, 'title' => 'role_view',],
            ['id' => 11, 'title' => 'role_delete',],
            ['id' => 12, 'title' => 'user_access',],
            ['id' => 13, 'title' => 'user_create',],
            ['id' => 14, 'title' => 'user_edit',],
            ['id' => 15, 'title' => 'user_view',],
            ['id' => 16, 'title' => 'user_delete',],
            ['id' => 17, 'title' => 'city_access',],
            ['id' => 18, 'title' => 'city_create',],
            ['id' => 19, 'title' => 'city_edit',],
            ['id' => 20, 'title' => 'city_view',],
            ['id' => 21, 'title' => 'city_delete',],
            ['id' => 22, 'title' => 'code_access',],
            ['id' => 23, 'title' => 'code_create',],
            ['id' => 24, 'title' => 'code_edit',],
            ['id' => 25, 'title' => 'code_view',],
            ['id' => 26, 'title' => 'code_delete',],
            ['id' => 27, 'title' => 'congress_access',],
            ['id' => 28, 'title' => 'congress_create',],
            ['id' => 29, 'title' => 'congress_edit',],
            ['id' => 30, 'title' => 'congress_view',],
            ['id' => 31, 'title' => 'congress_delete',],
            ['id' => 32, 'title' => 'congress_entry_access',],
            ['id' => 33, 'title' => 'congress_entry_create',],
            ['id' => 34, 'title' => 'congress_entry_edit',],
            ['id' => 35, 'title' => 'congress_entry_view',],
            ['id' => 36, 'title' => 'congress_entry_delete',],
            ['id' => 37, 'title' => 'congress_hotel_access',],
            ['id' => 38, 'title' => 'congress_hotel_create',],
            ['id' => 39, 'title' => 'congress_hotel_edit',],
            ['id' => 40, 'title' => 'congress_hotel_view',],
            ['id' => 41, 'title' => 'congress_hotel_delete',],
            ['id' => 42, 'title' => 'document_type_access',],
            ['id' => 43, 'title' => 'document_type_create',],
            ['id' => 44, 'title' => 'document_type_edit',],
            ['id' => 45, 'title' => 'document_type_view',],
            ['id' => 46, 'title' => 'document_type_delete',],
            ['id' => 47, 'title' => 'entry_access',],
            ['id' => 48, 'title' => 'entry_create',],
            ['id' => 49, 'title' => 'entry_edit',],
            ['id' => 50, 'title' => 'entry_view',],
            ['id' => 51, 'title' => 'entry_delete',],
            ['id' => 52, 'title' => 'images_hotel_access',],
            ['id' => 53, 'title' => 'images_hotel_create',],
            ['id' => 54, 'title' => 'images_hotel_edit',],
            ['id' => 55, 'title' => 'images_hotel_view',],
            ['id' => 56, 'title' => 'images_hotel_delete',],
            ['id' => 57, 'title' => 'province_access',],
            ['id' => 58, 'title' => 'province_create',],
            ['id' => 59, 'title' => 'province_edit',],
            ['id' => 60, 'title' => 'province_view',],
            ['id' => 61, 'title' => 'province_delete',],
            ['id' => 62, 'title' => 'registration_access',],
            ['id' => 63, 'title' => 'registration_create',],
            ['id' => 64, 'title' => 'registration_edit',],
            ['id' => 65, 'title' => 'registration_view',],
            ['id' => 66, 'title' => 'registration_delete',],
            ['id' => 67, 'title' => 'room_access',],
            ['id' => 68, 'title' => 'room_create',],
            ['id' => 69, 'title' => 'room_edit',],
            ['id' => 70, 'title' => 'room_view',],
            ['id' => 71, 'title' => 'room_delete',],
            ['id' => 72, 'title' => 'speaker_access',],
            ['id' => 73, 'title' => 'speaker_create',],
            ['id' => 74, 'title' => 'speaker_edit',],
            ['id' => 75, 'title' => 'speaker_view',],
            ['id' => 76, 'title' => 'speaker_delete',],
            ['id' => 77, 'title' => 'speakers_congress_access',],
            ['id' => 78, 'title' => 'speakers_congress_create',],
            ['id' => 79, 'title' => 'speakers_congress_edit',],
            ['id' => 80, 'title' => 'speakers_congress_view',],
            ['id' => 81, 'title' => 'speakers_congress_delete',],
            ['id' => 82, 'title' => 'hotel_access',],
            ['id' => 83, 'title' => 'hotel_create',],
            ['id' => 84, 'title' => 'hotel_edit',],
            ['id' => 85, 'title' => 'hotel_view',],
            ['id' => 86, 'title' => 'hotel_delete',],
            ['id' => 87, 'title' => 'image_access',],
            ['id' => 88, 'title' => 'image_create',],
            ['id' => 89, 'title' => 'image_edit',],
            ['id' => 90, 'title' => 'image_view',],
            ['id' => 91, 'title' => 'image_delete',],
            ['id' => 92, 'title' => 'user_action_access',],
            ['id' => 93, 'title' => 'user_action_create',],
            ['id' => 94, 'title' => 'user_action_edit',],
            ['id' => 95, 'title' => 'user_action_view',],
            ['id' => 96, 'title' => 'user_action_delete',],
            ['id' => 97, 'title' => 'faq_management_access',],
            ['id' => 98, 'title' => 'faq_management_create',],
            ['id' => 99, 'title' => 'faq_management_edit',],
            ['id' => 100, 'title' => 'faq_management_view',],
            ['id' => 101, 'title' => 'faq_management_delete',],
            ['id' => 102, 'title' => 'faq_category_access',],
            ['id' => 103, 'title' => 'faq_category_create',],
            ['id' => 104, 'title' => 'faq_category_edit',],
            ['id' => 105, 'title' => 'faq_category_view',],
            ['id' => 106, 'title' => 'faq_category_delete',],
            ['id' => 107, 'title' => 'faq_question_access',],
            ['id' => 108, 'title' => 'faq_question_create',],
            ['id' => 109, 'title' => 'faq_question_edit',],
            ['id' => 110, 'title' => 'faq_question_view',],
            ['id' => 111, 'title' => 'faq_question_delete',],
            ['id' => 112, 'title' => 'day_access',],
            ['id' => 113, 'title' => 'day_create',],
            ['id' => 114, 'title' => 'day_edit',],
            ['id' => 115, 'title' => 'day_view',],
            ['id' => 116, 'title' => 'day_delete',],
            ['id' => 117, 'title' => 'hall_access',],
            ['id' => 118, 'title' => 'hall_create',],
            ['id' => 119, 'title' => 'hall_edit',],
            ['id' => 120, 'title' => 'hall_view',],
            ['id' => 121, 'title' => 'hall_delete',],
            ['id' => 122, 'title' => 'event_access',],
            ['id' => 123, 'title' => 'event_create',],
            ['id' => 124, 'title' => 'event_edit',],
            ['id' => 125, 'title' => 'event_view',],
            ['id' => 126, 'title' => 'event_delete',],

        ];

        foreach ($items as $item) {
            \App\Permission::create($item);
        }
    }
}
